# Generated by Django 2.1 on 2018-10-26 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('num_rooms', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('user_rating', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('address', models.TextField(default='Address')),
                ('contact', models.CharField(default='123456789', max_length=100)),
                ('email', models.EmailField(default='hotel_name@email.com', max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=3, max_digits=4)),
                ('num_rating', models.PositiveIntegerField(default=0)),
                ('wallet', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='Deluxe', max_length=100)),
                ('occupancy', models.CharField(choices=[('SINGLE', 'SINGLE'), ('DOUBLE', 'DOUBLE')], default='SINGLE', max_length=50)),
                ('room_type', models.CharField(choices=[('A/C(Air Conditioned)', 'A/C(Air Conditioned)'), ('Non A/C(Non Air Conditioned)', 'Non A/C(Non Air Conditioned)')], default='Non A/C(Non Air Conditioned)', max_length=50)),
                ('maximum', models.PositiveIntegerField(default=10)),
                ('available', models.PositiveIntegerField(default=10)),
                ('cost', models.PositiveIntegerField(default=1000)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Transaction'),
        ),
    ]
